type Nullable<T> = T | null | undefined
export declare class ZorixCore {
    constructor(createEngine: (p0: (p0: Nullable<string>) => void) => JsEngine, storage: JsStorage, voice: JsVoice, readFile: (p0: string) => Promise<string>, cores: number);
    subscribe(listener: (p0: string, p1: any) => void): void;
    setLanguage(lang: string): void;
    setScreen(screen: string): void;
    onBackground(): void;
    onForeground(): void;
    speak(text: string): void;
    stopSpeaking(): void;
    voiceReady(): boolean;
    voiceStarted(token: number): void;
    voiceDone(token: number): void;
    close(): void;
    completeOnboarding(name: string, experience: string): void;
    rename(name: string): void;
    setSetting(key: string, value: string): void;
    boardMove(from: string, to: string): void;
    boardPromote(piece: string): void;
    boardUndo(): void;
    boardRedo(): void;
    boardGoTo(plies: number): void;
    boardNew(): void;
    boardFlip(): void;
    boardLoadFen(fen: string): Nullable<string>;
    boardLoadGame(startFen: string, moves: Array<string>): void;
    boardPgn(): string;
    boardFen(): string;
    boardBestMove(): void;
    boardStop(): void;
    boardPlaySuggestion(): void;
    boardDismissSuggestion(): void;
    boardAnalysis(on: boolean): void;
    boardPlayLine(index: number): void;
    boardSpeakFeedback(): void;
    boardSpeakHint(): void;
    boardSetPosition(fen: string): boolean;
    positionProblem(fen: string): Nullable<string>;
    bots(): Array<any>;
    recommendedLevel(): number;
    playStart(level: number, side: string): void;
    playRematch(): void;
    playClose(): void;
    playMove(from: string, to: string): void;
    playPromote(piece: string): void;
    playTakeback(): void;
    playHint(): void;
    playResign(): void;
    playOfferDraw(): void;
    playSpeakAgain(): void;
    reviewPlayGame(): void;
    reviewGame(startFen: string, moves: Array<string>, player: string): void;
    reviewGoTo(ply: number): void;
    reviewCancel(): void;
    reviewRetry(index: number): void;
    reviewEndRetry(): void;
    reviewRetryMove(uci: string): Nullable<void>;
    puzzleStart(mode: string, theme: Nullable<string>): void;
    puzzleNext(): void;
    puzzleMove(from: string, to: string): void;
    puzzlePromote(piece: string): void;
    puzzleHint(): void;
    puzzleSolution(): void;
    lessonStart(courseId: string, lessonId: string): boolean;
    lessonClose(): void;
    lessonNext(): Nullable<void>;
    lessonPrevious(): Nullable<void>;
    lessonRetry(): Nullable<void>;
    lessonMove(from: string, to: string): Nullable<void>;
    lessonPromote(piece: string): Nullable<void>;
    lessonSquare(square: string): Nullable<void>;
    lessonOption(index: number): Nullable<void>;
    lessonHint(): Nullable<void>;
    lessonSolution(): Nullable<void>;
}