// Generated by scripts/embed-migrations.mjs from ./drizzle — do not edit.
export const MIGRATIONS: { name: string; statements: string[] }[] = [
  {
    "name": "0000_init",
    "statements": [
      "CREATE TABLE \"activity\" (\n\t\"user_id\" uuid NOT NULL,\n\t\"day\" date NOT NULL,\n\t\"seconds\" integer DEFAULT 0 NOT NULL,\n\tCONSTRAINT \"activity_user_id_day_pk\" PRIMARY KEY(\"user_id\",\"day\")\n);",
      "CREATE TABLE \"codes\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"user_id\" uuid NOT NULL,\n\t\"purpose\" text NOT NULL,\n\t\"code_hash\" text NOT NULL,\n\t\"attempts\" integer DEFAULT 0 NOT NULL,\n\t\"expires_at\" timestamp with time zone NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"games\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"kind\" text NOT NULL,\n\t\"status\" text NOT NULL,\n\t\"creator_id\" uuid,\n\t\"invitee_id\" uuid,\n\t\"white_id\" uuid,\n\t\"black_id\" uuid,\n\t\"creator_color\" text DEFAULT 'random' NOT NULL,\n\t\"bot_level\" integer,\n\t\"moves\" text DEFAULT '' NOT NULL,\n\t\"fen\" text NOT NULL,\n\t\"ply\" integer DEFAULT 0 NOT NULL,\n\t\"result\" text,\n\t\"reason\" text,\n\t\"initial_ms\" integer DEFAULT 0 NOT NULL,\n\t\"increment_ms\" integer DEFAULT 0 NOT NULL,\n\t\"white_ms\" integer DEFAULT 0 NOT NULL,\n\t\"black_ms\" integer DEFAULT 0 NOT NULL,\n\t\"turn_started_at\" timestamp with time zone,\n\t\"draw_offer\" text,\n\t\"rematch_id\" text,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"finished_at\" timestamp with time zone\n);",
      "CREATE TABLE \"logins\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"user_id\" uuid,\n\t\"email\" text NOT NULL,\n\t\"success\" boolean NOT NULL,\n\t\"ip\" text,\n\t\"user_agent\" text,\n\t\"at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"sessions\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"user_id\" uuid NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"expires_at\" timestamp with time zone NOT NULL,\n\t\"last_seen_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"ip\" text,\n\t\"user_agent\" text\n);",
      "CREATE TABLE \"site_settings\" (\n\t\"key\" text PRIMARY KEY NOT NULL,\n\t\"value\" text NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"user_state\" (\n\t\"user_id\" uuid PRIMARY KEY NOT NULL,\n\t\"data\" jsonb DEFAULT '{}'::jsonb NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"users\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"email\" text NOT NULL,\n\t\"username\" text NOT NULL,\n\t\"password_hash\" text NOT NULL,\n\t\"verified\" boolean DEFAULT false NOT NULL,\n\t\"role\" text DEFAULT 'user' NOT NULL,\n\t\"banned\" boolean DEFAULT false NOT NULL,\n\t\"lang\" text,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"last_seen_at\" timestamp with time zone,\n\t\"last_login_at\" timestamp with time zone,\n\t\"login_count\" integer DEFAULT 0 NOT NULL,\n\t\"seconds_online\" integer DEFAULT 0 NOT NULL\n);",
      "ALTER TABLE \"activity\" ADD CONSTRAINT \"activity_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"codes\" ADD CONSTRAINT \"codes_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"games\" ADD CONSTRAINT \"games_creator_id_users_id_fk\" FOREIGN KEY (\"creator_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE set null ON UPDATE no action;",
      "ALTER TABLE \"games\" ADD CONSTRAINT \"games_invitee_id_users_id_fk\" FOREIGN KEY (\"invitee_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE set null ON UPDATE no action;",
      "ALTER TABLE \"games\" ADD CONSTRAINT \"games_white_id_users_id_fk\" FOREIGN KEY (\"white_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE set null ON UPDATE no action;",
      "ALTER TABLE \"games\" ADD CONSTRAINT \"games_black_id_users_id_fk\" FOREIGN KEY (\"black_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE set null ON UPDATE no action;",
      "ALTER TABLE \"logins\" ADD CONSTRAINT \"logins_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE set null ON UPDATE no action;",
      "ALTER TABLE \"sessions\" ADD CONSTRAINT \"sessions_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"user_state\" ADD CONSTRAINT \"user_state_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "CREATE INDEX \"activity_day_idx\" ON \"activity\" USING btree (\"day\");",
      "CREATE INDEX \"codes_user_idx\" ON \"codes\" USING btree (\"user_id\",\"purpose\");",
      "CREATE INDEX \"games_white_idx\" ON \"games\" USING btree (\"white_id\");",
      "CREATE INDEX \"games_black_idx\" ON \"games\" USING btree (\"black_id\");",
      "CREATE INDEX \"games_invitee_idx\" ON \"games\" USING btree (\"invitee_id\",\"status\");",
      "CREATE INDEX \"games_created_idx\" ON \"games\" USING btree (\"created_at\");",
      "CREATE INDEX \"logins_at_idx\" ON \"logins\" USING btree (\"at\");",
      "CREATE INDEX \"logins_user_idx\" ON \"logins\" USING btree (\"user_id\");",
      "CREATE INDEX \"sessions_user_idx\" ON \"sessions\" USING btree (\"user_id\");",
      "CREATE UNIQUE INDEX \"users_email_idx\" ON \"users\" USING btree (lower(\"email\"));",
      "CREATE UNIQUE INDEX \"users_username_idx\" ON \"users\" USING btree (lower(\"username\"));"
    ]
  }
];
