package com.zorix.chess.learn

import com.zorix.chess.core.Move

// Generated by mobile/content/tools/openings.py - do not edit by hand.

/** A named opening line. [moves] are UCI moves from the initial position. */
class Opening(val id: String, val eco: String, private val names: Map<String, String>, val moves: List<String>, val san: String) {
    fun name(lang: String): String = names[lang] ?: names.getValue("en")
}

/** Opening names for the coach ("Book move: Sicilian Defense") and the opening lessons. */
object OpeningBook {
    val all: List<Opening> = listOf(
        Opening("kings-pawn", "C20", mapOf("en" to "King's Pawn Game", "fa" to "بازی سرباز شاه", "ckb" to "یاریی سەربازی شا"), "e2e4 e7e5".split(' '), "e4 e5"),
        Opening("italian", "C50", mapOf("en" to "Italian Game", "fa" to "گشایش ایتالیایی", "ckb" to "دەستپێکی ئیتاڵی"), "e2e4 e7e5 g1f3 b8c6 f1c4".split(' '), "e4 e5 Nf3 Nc6 Bc4"),
        Opening("giuoco-piano", "C53", mapOf("en" to "Italian Game: Giuoco Piano", "fa" to "گشایش ایتالیایی: جوکو پیانو", "ckb" to "دەستپێکی ئیتاڵی: جۆکۆ پیانۆ"), "e2e4 e7e5 g1f3 b8c6 f1c4 f8c5 c2c3 g8f6 d2d4".split(' '), "e4 e5 Nf3 Nc6 Bc4 Bc5 c3 Nf6 d4"),
        Opening("giuoco-pianissimo", "C54", mapOf("en" to "Italian Game: Giuoco Pianissimo", "fa" to "گشایش ایتالیایی: جوکو پیانیسیمو", "ckb" to "دەستپێکی ئیتاڵی: جۆکۆ پیانیسیمۆ"), "e2e4 e7e5 g1f3 b8c6 f1c4 f8c5 c2c3 g8f6 d2d3".split(' '), "e4 e5 Nf3 Nc6 Bc4 Bc5 c3 Nf6 d3"),
        Opening("evans-gambit", "C51", mapOf("en" to "Evans Gambit", "fa" to "گامبی ایوانز", "ckb" to "گامبیتی ئیڤانس"), "e2e4 e7e5 g1f3 b8c6 f1c4 f8c5 b2b4".split(' '), "e4 e5 Nf3 Nc6 Bc4 Bc5 b4"),
        Opening("two-knights", "C55", mapOf("en" to "Two Knights Defense", "fa" to "دفاع دو اسب", "ckb" to "بەرگریی دوو ئەسپ"), "e2e4 e7e5 g1f3 b8c6 f1c4 g8f6".split(' '), "e4 e5 Nf3 Nc6 Bc4 Nf6"),
        Opening("fried-liver", "C57", mapOf("en" to "Two Knights: Fried Liver Attack", "fa" to "دفاع دو اسب: حمله‌ی جگر سرخ‌کرده", "ckb" to "دوو ئەسپ: هێرشی جگەری سوورکراو"), "e2e4 e7e5 g1f3 b8c6 f1c4 g8f6 f3g5 d7d5 e4d5 f6d5 g5f7".split(' '), "e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5 d5 exd5 Nxd5 Nxf7"),
        Opening("two-knights-na5", "C58", mapOf("en" to "Two Knights: Main Line", "fa" to "دفاع دو اسب: خط اصلی", "ckb" to "دوو ئەسپ: هێڵی سەرەکی"), "e2e4 e7e5 g1f3 b8c6 f1c4 g8f6 f3g5 d7d5 e4d5 c6a5".split(' '), "e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5 d5 exd5 Na5"),
        Opening("ruy-lopez", "C60", mapOf("en" to "Ruy Lopez (Spanish Game)", "fa" to "گشایش روی لوپز (اسپانیایی)", "ckb" to "ڕوی لۆپێز (یاریی ئیسپانی)"), "e2e4 e7e5 g1f3 b8c6 f1b5".split(' '), "e4 e5 Nf3 Nc6 Bb5"),
        Opening("ruy-morphy", "C70", mapOf("en" to "Ruy Lopez: Morphy Defense", "fa" to "روی لوپز: دفاع مورفی", "ckb" to "ڕوی لۆپێز: بەرگریی مۆرفی"), "e2e4 e7e5 g1f3 b8c6 f1b5 a7a6 b5a4".split(' '), "e4 e5 Nf3 Nc6 Bb5 a6 Ba4"),
        Opening("ruy-closed", "C84", mapOf("en" to "Ruy Lopez: Closed", "fa" to "روی لوپز: بسته", "ckb" to "ڕوی لۆپێز: داخراو"), "e2e4 e7e5 g1f3 b8c6 f1b5 a7a6 b5a4 g8f6 e1g1 f8e7 f1e1 b7b5 a4b3 d7d6 c2c3 e8g8".split(' '), "e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Be7 Re1 b5 Bb3 d6 c3 O-O"),
        Opening("ruy-exchange", "C68", mapOf("en" to "Ruy Lopez: Exchange Variation", "fa" to "روی لوپز: واریانت تعویض", "ckb" to "ڕوی لۆپێز: گۆڕینەوە"), "e2e4 e7e5 g1f3 b8c6 f1b5 a7a6 b5c6 d7c6".split(' '), "e4 e5 Nf3 Nc6 Bb5 a6 Bxc6 dxc6"),
        Opening("berlin", "C65", mapOf("en" to "Ruy Lopez: Berlin Defense", "fa" to "روی لوپز: دفاع برلین", "ckb" to "ڕوی لۆپێز: بەرگریی بەرلین"), "e2e4 e7e5 g1f3 b8c6 f1b5 g8f6".split(' '), "e4 e5 Nf3 Nc6 Bb5 Nf6"),
        Opening("scotch", "C45", mapOf("en" to "Scotch Game", "fa" to "گشایش اسکاتلندی", "ckb" to "یاریی سکۆتلەندی"), "e2e4 e7e5 g1f3 b8c6 d2d4 e5d4 f3d4".split(' '), "e4 e5 Nf3 Nc6 d4 exd4 Nxd4"),
        Opening("scotch-gambit", "C44", mapOf("en" to "Scotch Gambit", "fa" to "گامبی اسکاتلندی", "ckb" to "گامبیتی سکۆتلەندی"), "e2e4 e7e5 g1f3 b8c6 d2d4 e5d4 f1c4".split(' '), "e4 e5 Nf3 Nc6 d4 exd4 Bc4"),
        Opening("four-knights", "C47", mapOf("en" to "Four Knights Game", "fa" to "بازی چهار اسب", "ckb" to "یاریی چوار ئەسپ"), "e2e4 e7e5 g1f3 b8c6 b1c3 g8f6".split(' '), "e4 e5 Nf3 Nc6 Nc3 Nf6"),
        Opening("petrov", "C42", mapOf("en" to "Petrov's Defense", "fa" to "دفاع پتروف", "ckb" to "بەرگریی پێترۆف"), "e2e4 e7e5 g1f3 g8f6".split(' '), "e4 e5 Nf3 Nf6"),
        Opening("philidor", "C41", mapOf("en" to "Philidor Defense", "fa" to "دفاع فیلیدور", "ckb" to "بەرگریی فیلیدۆر"), "e2e4 e7e5 g1f3 d7d6".split(' '), "e4 e5 Nf3 d6"),
        Opening("kings-gambit", "C30", mapOf("en" to "King's Gambit", "fa" to "گامبی شاه", "ckb" to "گامبیتی شا"), "e2e4 e7e5 f2f4".split(' '), "e4 e5 f4"),
        Opening("kings-gambit-accepted", "C33", mapOf("en" to "King's Gambit Accepted", "fa" to "گامبی شاه پذیرفته‌شده", "ckb" to "گامبیتی شای وەرگیراو"), "e2e4 e7e5 f2f4 e5f4".split(' '), "e4 e5 f4 exf4"),
        Opening("vienna", "C25", mapOf("en" to "Vienna Game", "fa" to "گشایش وین", "ckb" to "یاریی ڤیەننا"), "e2e4 e7e5 b1c3".split(' '), "e4 e5 Nc3"),
        Opening("center-game", "C22", mapOf("en" to "Center Game", "fa" to "بازی مرکزی", "ckb" to "یاریی ناوەند"), "e2e4 e7e5 d2d4 e5d4 d1d4".split(' '), "e4 e5 d4 exd4 Qxd4"),
        Opening("latvian", "C40", mapOf("en" to "Latvian Gambit", "fa" to "گامبی لتونیایی", "ckb" to "گامبیتی لاتڤی"), "e2e4 e7e5 g1f3 f7f5".split(' '), "e4 e5 Nf3 f5"),
        Opening("sicilian", "B20", mapOf("en" to "Sicilian Defense", "fa" to "دفاع سیسیلی", "ckb" to "بەرگریی سیسیلی"), "e2e4 c7c5".split(' '), "e4 c5"),
        Opening("sicilian-open", "B32", mapOf("en" to "Sicilian Defense: Open", "fa" to "دفاع سیسیلی: باز", "ckb" to "سیسیلی: کراوە"), "e2e4 c7c5 g1f3 b8c6 d2d4 c5d4 f3d4".split(' '), "e4 c5 Nf3 Nc6 d4 cxd4 Nxd4"),
        Opening("najdorf", "B90", mapOf("en" to "Sicilian: Najdorf Variation", "fa" to "دفاع سیسیلی: واریانت نایدورف", "ckb" to "سیسیلی: نایدۆرف"), "e2e4 c7c5 g1f3 d7d6 d2d4 c5d4 f3d4 g8f6 b1c3 a7a6".split(' '), "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6"),
        Opening("dragon", "B70", mapOf("en" to "Sicilian: Dragon Variation", "fa" to "دفاع سیسیلی: واریانت اژدها", "ckb" to "سیسیلی: ئەژدیها"), "e2e4 c7c5 g1f3 d7d6 d2d4 c5d4 f3d4 g8f6 b1c3 g7g6".split(' '), "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 g6"),
        Opening("sicilian-classical", "B56", mapOf("en" to "Sicilian: Classical Variation", "fa" to "دفاع سیسیلی: کلاسیک", "ckb" to "سیسیلی: کلاسیک"), "e2e4 c7c5 g1f3 d7d6 d2d4 c5d4 f3d4 g8f6 b1c3 b8c6".split(' '), "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 Nc6"),
        Opening("scheveningen", "B80", mapOf("en" to "Sicilian: Scheveningen Variation", "fa" to "دفاع سیسیلی: شوننینگن", "ckb" to "سیسیلی: شێڤێنینگن"), "e2e4 c7c5 g1f3 d7d6 d2d4 c5d4 f3d4 g8f6 b1c3 e7e6".split(' '), "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 e6"),
        Opening("sveshnikov", "B33", mapOf("en" to "Sicilian: Sveshnikov Variation", "fa" to "دفاع سیسیلی: سوشنیکوف", "ckb" to "سیسیلی: سڤێشنیکۆڤ"), "e2e4 c7c5 g1f3 b8c6 d2d4 c5d4 f3d4 g8f6 b1c3 e7e5".split(' '), "e4 c5 Nf3 Nc6 d4 cxd4 Nxd4 Nf6 Nc3 e5"),
        Opening("taimanov", "B46", mapOf("en" to "Sicilian: Taimanov Variation", "fa" to "دفاع سیسیلی: تایمانوف", "ckb" to "سیسیلی: تایمانۆڤ"), "e2e4 c7c5 g1f3 e7e6 d2d4 c5d4 f3d4 b8c6".split(' '), "e4 c5 Nf3 e6 d4 cxd4 Nxd4 Nc6"),
        Opening("alapin", "B22", mapOf("en" to "Sicilian: Alapin Variation", "fa" to "دفاع سیسیلی: آلاپین", "ckb" to "سیسیلی: ئالاپین"), "e2e4 c7c5 c2c3".split(' '), "e4 c5 c3"),
        Opening("closed-sicilian", "B23", mapOf("en" to "Sicilian: Closed", "fa" to "دفاع سیسیلی: بسته", "ckb" to "سیسیلی: داخراو"), "e2e4 c7c5 b1c3".split(' '), "e4 c5 Nc3"),
        Opening("smith-morra", "B21", mapOf("en" to "Sicilian: Smith-Morra Gambit", "fa" to "سیسیلی: گامبی اسمیت-مورا", "ckb" to "سیسیلی: گامبیتی سمیس-مۆڕا"), "e2e4 c7c5 d2d4 c5d4 c2c3".split(' '), "e4 c5 d4 cxd4 c3"),
        Opening("rossolimo", "B31", mapOf("en" to "Sicilian: Rossolimo Variation", "fa" to "سیسیلی: روسولیمو", "ckb" to "سیسیلی: ڕۆسۆلیمۆ"), "e2e4 c7c5 g1f3 b8c6 f1b5".split(' '), "e4 c5 Nf3 Nc6 Bb5"),
        Opening("french", "C00", mapOf("en" to "French Defense", "fa" to "دفاع فرانسوی", "ckb" to "بەرگریی فەرەنسی"), "e2e4 e7e6".split(' '), "e4 e6"),
        Opening("french-main", "C10", mapOf("en" to "French Defense: Main Line", "fa" to "دفاع فرانسوی: خط اصلی", "ckb" to "بەرگریی فەرەنسی: هێڵی سەرەکی"), "e2e4 e7e6 d2d4 d7d5".split(' '), "e4 e6 d4 d5"),
        Opening("french-advance", "C02", mapOf("en" to "French: Advance Variation", "fa" to "دفاع فرانسوی: پیشروی", "ckb" to "فەرەنسی: پێشڕەوی"), "e2e4 e7e6 d2d4 d7d5 e4e5 c7c5 c2c3 b8c6 g1f3".split(' '), "e4 e6 d4 d5 e5 c5 c3 Nc6 Nf3"),
        Opening("french-winawer", "C15", mapOf("en" to "French: Winawer Variation", "fa" to "دفاع فرانسوی: وینآور", "ckb" to "فەرەنسی: ڤینەوەر"), "e2e4 e7e6 d2d4 d7d5 b1c3 f8b4".split(' '), "e4 e6 d4 d5 Nc3 Bb4"),
        Opening("french-classical", "C11", mapOf("en" to "French: Classical Variation", "fa" to "دفاع فرانسوی: کلاسیک", "ckb" to "فەرەنسی: کلاسیک"), "e2e4 e7e6 d2d4 d7d5 b1c3 g8f6".split(' '), "e4 e6 d4 d5 Nc3 Nf6"),
        Opening("french-tarrasch", "C03", mapOf("en" to "French: Tarrasch Variation", "fa" to "دفاع فرانسوی: تاراش", "ckb" to "فەرەنسی: تاراش"), "e2e4 e7e6 d2d4 d7d5 b1d2".split(' '), "e4 e6 d4 d5 Nd2"),
        Opening("french-exchange", "C01", mapOf("en" to "French: Exchange Variation", "fa" to "دفاع فرانسوی: تعویض", "ckb" to "فەرەنسی: گۆڕینەوە"), "e2e4 e7e6 d2d4 d7d5 e4d5 e6d5".split(' '), "e4 e6 d4 d5 exd5 exd5"),
        Opening("caro-kann", "B10", mapOf("en" to "Caro-Kann Defense", "fa" to "دفاع کاروکان", "ckb" to "بەرگریی کارۆ-کان"), "e2e4 c7c6".split(' '), "e4 c6"),
        Opening("caro-classical", "B18", mapOf("en" to "Caro-Kann: Classical Variation", "fa" to "کاروکان: کلاسیک", "ckb" to "کارۆ-کان: کلاسیک"), "e2e4 c7c6 d2d4 d7d5 b1c3 d5e4 c3e4 c8f5".split(' '), "e4 c6 d4 d5 Nc3 dxe4 Nxe4 Bf5"),
        Opening("caro-advance", "B12", mapOf("en" to "Caro-Kann: Advance Variation", "fa" to "کاروکان: پیشروی", "ckb" to "کارۆ-کان: پێشڕەوی"), "e2e4 c7c6 d2d4 d7d5 e4e5 c8f5".split(' '), "e4 c6 d4 d5 e5 Bf5"),
        Opening("caro-exchange", "B13", mapOf("en" to "Caro-Kann: Exchange Variation", "fa" to "کاروکان: تعویض", "ckb" to "کارۆ-کان: گۆڕینەوە"), "e2e4 c7c6 d2d4 d7d5 e4d5 c6d5".split(' '), "e4 c6 d4 d5 exd5 cxd5"),
        Opening("scandinavian", "B01", mapOf("en" to "Scandinavian Defense", "fa" to "دفاع اسکاندیناوی", "ckb" to "بەرگریی سکاندیناڤی"), "e2e4 d7d5".split(' '), "e4 d5"),
        Opening("scandinavian-main", "B01", mapOf("en" to "Scandinavian: Main Line", "fa" to "دفاع اسکاندیناوی: خط اصلی", "ckb" to "سکاندیناڤی: هێڵی سەرەکی"), "e2e4 d7d5 e4d5 d8d5 b1c3 d5a5".split(' '), "e4 d5 exd5 Qxd5 Nc3 Qa5"),
        Opening("pirc", "B07", mapOf("en" to "Pirc Defense", "fa" to "دفاع پیرتس", "ckb" to "بەرگریی پیرتس"), "e2e4 d7d6 d2d4 g8f6 b1c3 g7g6".split(' '), "e4 d6 d4 Nf6 Nc3 g6"),
        Opening("modern", "B06", mapOf("en" to "Modern Defense", "fa" to "دفاع مدرن", "ckb" to "بەرگریی مۆدێرن"), "e2e4 g7g6".split(' '), "e4 g6"),
        Opening("alekhine", "B02", mapOf("en" to "Alekhine's Defense", "fa" to "دفاع آلخین", "ckb" to "بەرگریی ئەلێخین"), "e2e4 g8f6".split(' '), "e4 Nf6"),
        Opening("queens-pawn", "D00", mapOf("en" to "Queen's Pawn Game", "fa" to "بازی سرباز وزیر", "ckb" to "یاریی سەربازی وەزیر"), "d2d4 d7d5".split(' '), "d4 d5"),
        Opening("queens-gambit", "D06", mapOf("en" to "Queen's Gambit", "fa" to "گامبی وزیر", "ckb" to "گامبیتی وەزیر"), "d2d4 d7d5 c2c4".split(' '), "d4 d5 c4"),
        Opening("qgd", "D30", mapOf("en" to "Queen's Gambit Declined", "fa" to "گامبی وزیر پذیرفته‌نشده", "ckb" to "گامبیتی وەزیری ڕەتکراو"), "d2d4 d7d5 c2c4 e7e6".split(' '), "d4 d5 c4 e6"),
        Opening("qgd-main", "D37", mapOf("en" to "Queen's Gambit Declined: Main Line", "fa" to "گامبی وزیر پذیرفته‌نشده: خط اصلی", "ckb" to "گامبیتی وەزیری ڕەتکراو: هێڵی سەرەکی"), "d2d4 d7d5 c2c4 e7e6 b1c3 g8f6 g1f3 f8e7".split(' '), "d4 d5 c4 e6 Nc3 Nf6 Nf3 Be7"),
        Opening("qga", "D20", mapOf("en" to "Queen's Gambit Accepted", "fa" to "گامبی وزیر پذیرفته‌شده", "ckb" to "گامبیتی وەزیری وەرگیراو"), "d2d4 d7d5 c2c4 d5c4".split(' '), "d4 d5 c4 dxc4"),
        Opening("slav", "D10", mapOf("en" to "Slav Defense", "fa" to "دفاع اسلاو", "ckb" to "بەرگریی سلاڤ"), "d2d4 d7d5 c2c4 c7c6".split(' '), "d4 d5 c4 c6"),
        Opening("semi-slav", "D43", mapOf("en" to "Semi-Slav Defense", "fa" to "دفاع نیمه‌اسلاو", "ckb" to "بەرگریی نیوە-سلاڤ"), "d2d4 d7d5 c2c4 c7c6 g1f3 g8f6 b1c3 e7e6".split(' '), "d4 d5 c4 c6 Nf3 Nf6 Nc3 e6"),
        Opening("albin", "D08", mapOf("en" to "Albin Countergambit", "fa" to "ضدگامبی آلبین", "ckb" to "دژەگامبیتی ئەلبین"), "d2d4 d7d5 c2c4 e7e5".split(' '), "d4 d5 c4 e5"),
        Opening("london", "D02", mapOf("en" to "London System", "fa" to "سیستم لندن", "ckb" to "سیستەمی لەندەن"), "d2d4 d7d5 c1f4".split(' '), "d4 d5 Bf4"),
        Opening("london-nf6", "A46", mapOf("en" to "London System (1...Nf6)", "fa" to "سیستم لندن (با اسب f6)", "ckb" to "سیستەمی لەندەن (ئەسپ f6)"), "d2d4 g8f6 c1f4".split(' '), "d4 Nf6 Bf4"),
        Opening("london-main", "D02", mapOf("en" to "London System: Main Setup", "fa" to "سیستم لندن: آرایش اصلی", "ckb" to "سیستەمی لەندەن: ڕێکخستنی سەرەکی"), "d2d4 d7d5 c1f4 g8f6 e2e3 e7e6 g1f3 c7c5 c2c3".split(' '), "d4 d5 Bf4 Nf6 e3 e6 Nf3 c5 c3"),
        Opening("indian", "A45", mapOf("en" to "Indian Defense", "fa" to "دفاع هندی", "ckb" to "بەرگریی هیندی"), "d2d4 g8f6".split(' '), "d4 Nf6"),
        Opening("kings-indian", "E60", mapOf("en" to "King's Indian Defense", "fa" to "دفاع هندی شاه", "ckb" to "بەرگریی هیندیی شا"), "d2d4 g8f6 c2c4 g7g6 b1c3 f8g7 e2e4 d7d6".split(' '), "d4 Nf6 c4 g6 Nc3 Bg7 e4 d6"),
        Opening("kings-indian-classical", "E92", mapOf("en" to "King's Indian: Classical", "fa" to "دفاع هندی شاه: کلاسیک", "ckb" to "هیندیی شا: کلاسیک"), "d2d4 g8f6 c2c4 g7g6 b1c3 f8g7 e2e4 d7d6 g1f3 e8g8 f1e2 e7e5".split(' '), "d4 Nf6 c4 g6 Nc3 Bg7 e4 d6 Nf3 O-O Be2 e5"),
        Opening("nimzo-indian", "E20", mapOf("en" to "Nimzo-Indian Defense", "fa" to "دفاع نیمزو-هندی", "ckb" to "بەرگریی نیمزۆ-هیندی"), "d2d4 g8f6 c2c4 e7e6 b1c3 f8b4".split(' '), "d4 Nf6 c4 e6 Nc3 Bb4"),
        Opening("queens-indian", "E12", mapOf("en" to "Queen's Indian Defense", "fa" to "دفاع هندی وزیر", "ckb" to "بەرگریی هیندیی وەزیر"), "d2d4 g8f6 c2c4 e7e6 g1f3 b7b6".split(' '), "d4 Nf6 c4 e6 Nf3 b6"),
        Opening("grunfeld", "D80", mapOf("en" to "Grünfeld Defense", "fa" to "دفاع گرونفلد", "ckb" to "بەرگریی گرونفێلد"), "d2d4 g8f6 c2c4 g7g6 b1c3 d7d5".split(' '), "d4 Nf6 c4 g6 Nc3 d5"),
        Opening("catalan", "E01", mapOf("en" to "Catalan Opening", "fa" to "گشایش کاتالان", "ckb" to "دەستپێکی کاتالان"), "d2d4 g8f6 c2c4 e7e6 g2g3".split(' '), "d4 Nf6 c4 e6 g3"),
        Opening("benoni", "A60", mapOf("en" to "Modern Benoni", "fa" to "دفاع بنونی مدرن", "ckb" to "بێنۆنیی مۆدێرن"), "d2d4 g8f6 c2c4 c7c5 d4d5 e7e6".split(' '), "d4 Nf6 c4 c5 d5 e6"),
        Opening("benko", "A57", mapOf("en" to "Benko Gambit", "fa" to "گامبی بنکو", "ckb" to "گامبیتی بێنکۆ"), "d2d4 g8f6 c2c4 c7c5 d4d5 b7b5".split(' '), "d4 Nf6 c4 c5 d5 b5"),
        Opening("dutch", "A80", mapOf("en" to "Dutch Defense", "fa" to "دفاع هلندی", "ckb" to "بەرگریی هۆڵەندی"), "d2d4 f7f5".split(' '), "d4 f5"),
        Opening("trompowsky", "A45", mapOf("en" to "Trompowsky Attack", "fa" to "حمله‌ی ترومپوفسکی", "ckb" to "هێرشی ترۆمپۆڤسکی"), "d2d4 g8f6 c1g5".split(' '), "d4 Nf6 Bg5"),
        Opening("englund", "A40", mapOf("en" to "Englund Gambit", "fa" to "گامبی انگلوند", "ckb" to "گامبیتی ئینگلوند"), "d2d4 e7e5".split(' '), "d4 e5"),
        Opening("english", "A10", mapOf("en" to "English Opening", "fa" to "گشایش انگلیسی", "ckb" to "دەستپێکی ئینگلیزی"), "c2c4".split(' '), "c4"),
        Opening("english-reversed-sicilian", "A20", mapOf("en" to "English: Reversed Sicilian", "fa" to "گشایش انگلیسی: سیسیلی معکوس", "ckb" to "ئینگلیزی: سیسیلیی پێچەوانە"), "c2c4 e7e5".split(' '), "c4 e5"),
        Opening("english-symmetrical", "A30", mapOf("en" to "English: Symmetrical", "fa" to "گشایش انگلیسی: قرینه", "ckb" to "ئینگلیزی: هاوتەریب"), "c2c4 c7c5".split(' '), "c4 c5"),
        Opening("reti", "A04", mapOf("en" to "Réti Opening", "fa" to "گشایش رتی", "ckb" to "دەستپێکی ڕێتی"), "g1f3".split(' '), "Nf3"),
        Opening("reti-main", "A09", mapOf("en" to "Réti Opening: Main Line", "fa" to "گشایش رتی: خط اصلی", "ckb" to "ڕێتی: هێڵی سەرەکی"), "g1f3 d7d5 c2c4".split(' '), "Nf3 d5 c4"),
        Opening("kings-indian-attack", "A07", mapOf("en" to "King's Indian Attack", "fa" to "حمله‌ی هندی شاه", "ckb" to "هێرشی هیندیی شا"), "g1f3 d7d5 g2g3 g8f6 f1g2 e7e6 e1g1".split(' '), "Nf3 d5 g3 Nf6 Bg2 e6 O-O"),
        Opening("larsen", "A01", mapOf("en" to "Nimzo-Larsen Attack", "fa" to "حمله‌ی نیمزو-لارسن", "ckb" to "هێرشی نیمزۆ-لارسن"), "b2b3".split(' '), "b3"),
        Opening("birds", "A02", mapOf("en" to "Bird's Opening", "fa" to "گشایش برد", "ckb" to "دەستپێکی بێرد"), "f2f4".split(' '), "f4"),
    )

    private val byId = all.associateBy { it.id }

    fun byId(id: String): Opening? = byId[id]

    /** True when the game from the initial position is still inside some opening line. */
    fun isBook(moves: List<Move>): Boolean {
        if (moves.isEmpty()) return true
        val uci = moves.map { it.uci }
        return all.any { o -> o.moves.size >= uci.size && o.moves.subList(0, uci.size) == uci }
    }

    /** The most specific opening whose whole line has been played, if any. */
    fun name(moves: List<Move>): Opening? {
        val uci = moves.map { it.uci }
        return all.filter { o -> o.moves.size <= uci.size && uci.subList(0, o.moves.size) == o.moves }
            .maxByOrNull { it.moves.size }
    }
}
